### ISSUE TITLE
state bar have a small square is displayed

### ISSUE THREAD

**Issue by yanboyang713** [UtkarshVerma/dwmblocks-async#13]
Hello Guys,

Good day to you.

I have a small square is displayed at the front of the **time**, Anyone knows what is the reason for this issue?
![](http://res.cloudinary.com/dkvj6mo4c/image/upload/v1642311208/screenshot/nzssl1flpg5t1hyid48v.png)

I also have another question.

I saw the NOTE below.

Please note that if you are using dwm-flexipatch, then you only need to enable the statuscmd patch through patches.h. There is no need to edit change the definition of getstatusbarpid() as the changes have already been applied there through dwm-flexipatch#190.

I also using dwm-flexipatch now. May I ask which statuscmd patch are you enabled?
Currently, I am enabled:
```c
#define BAR_DWMBLOCKS_PATCH 1
#define BAR_STATUS2D_PATCH 1
```

Are there any other patches that need to enable?

Thanks,
Boyang Yan

**Comment by UtkarshVerma** [comment]
The square blocks are the because you  enabled clickability in dwmblocks using `#define CLICKABLE_BLOCKS`  but didn't enable `statuscmd` patch in dwm.  You have the correct macros defined from what you've told me. Did you define them in `config.h`.

Here's mine for your reference: https://github.com/UtkarshVerma/dwm-flexipatch/blob/mine/patches.h

**Comment by yanboyang713** [comment]
Hello @UtkarshVerma ,

Thanks for your reply.

I found you have enabled so many patches. I am testing those one by one.

When I change
```c
#define BAR_STATUSCMD_PATCH 1
#define BAR_STATUS_PATCH 0
```
The square is gone.

Currently, 
![](http://res.cloudinary.com/dkvj6mo4c/image/upload/v1642337472/screenshot/q0mhn5gdr2eeriu50bv7.png)

Currently, the size is too small. Do you know have to change the size? 

Thanks so much for your help.
Boyang Yan

**Comment by UtkarshVerma** [comment]
Oh, yeah. `statuscmd` patch is required in `dwm` which is why you needed to define the macro. Regarding the font size, that is `dwm`'s business. You could play around with `fontconfig` or the `font2` patch for `dwm`, but I won't be able to help you with that.

I am closing this issue as it has been solved. If you face any bugs, related to this issue, you may reopen it.

**Comment by yanboyang713** [comment]
Thanks @UtkarshVerma
