### ISSUE TITLE
No icon support in dwmblocks-async

### ISSUE THREAD

**Issue by JimPix1** [UtkarshVerma/dwmblocks-async#20]
In Luke's dwmblocks you could set icons however this seems to have been removed entirely in dwmblocks-async.. why?
Do I now need to manually set the icon in the script?

**Comment by UtkarshVerma** [comment]
Yes, the icons field has been removed intentionally.

This is because setting the icon in the script allows for dynamic icons. For example, you'd want to change the volume icon to mute when volume is zero.

Also, if you have a script called `sb-foo`, and you want a static icon, then you can simply write `echo "$icon $(sb-foo)"` as your block command.
