### ISSUE TITLE
Status bar not showing up

### ISSUE THREAD

**Issue by pter1342** [UtkarshVerma/dwmblocks-async#39]
- I have added dwmblocks & to my .xinitrc
- I have installed statuscmd patch to dwm
- dwmblocks has a pid and is running
- ~/.local/bin/ scripts are ran

yet when it's ran, all I have is a single square in place where it should be on the rightmost side of the status bar, like this

![image](https://user-images.githubusercontent.com/99407909/203060033-f0b55146-e9f6-4646-861f-99dc52475296.png)

Any idea what could be the issue?

Operating System: Void Linux
Kernel: 6.0.9_1
dwm-6.4
zsh 5.9

**Comment by UtkarshVerma** [comment]
Can you please try disabling clickability in dwmblocks and let me know if you get any status?

**Comment by pter1342** [comment]
> Can you please try disabling clickability in dwmblocks and let me know if you get any status?

Just tried it, no change, running dwmblocks in terminal after killing it yields no output

**Comment by pter1342** [comment]
regular dwmblocks seems to be displaying just fine, but trying to run dwmblocks-async displays nothing at all

**Comment by Crisis82** [comment]
I have this issue too. I'll give you some hints about the possible cause:
- the empty box in the image is the one in the battery script for the unavailable match. (I tried to remove it from the script and is no more showing up)
- are displayed only the "issues" like the battery unavailable status or the wifi not connected, although the battery is okay and if I run the command from shell it gives me Discharging correctly.
In fact now that I removed the unavailable battery icon and I connected to a wifi, it's displayed nothing (xsetroot is not updated).
Disabling the clickability, changing the command length value and the delimiter, didn't solved.
I also noted that the script didn't updated when changing the config.h file because the dwmblocks output file was not overridden (don't know why), but manualy removing the file and re-generating it fixed this problem.

I'm on Void Linux too, and my scripts are under $HOME/.config/ .

**Comment by Crisis82** [comment]
Ok I found the issue. If also you copied the ```sb-them``` script from @UtkarshVerma dotfiles linked in the repo, at the end of the file there is a case loop, but the STATUSBAR variable isn't set, so it exit without printing anything. You have to remove everything except for the line executed in the dwmblocks case (```echo $args "^c$colors^ $1"```). There is also another error I think, because with ^C doesn't interprets colors, so you have to put a lowercase c. Moreover the color associations in the script for me didn't work and made dwmblocks exit, so I substitued them with hexadecimal colors and everything worked.
@pter1342 If you need help feel free to check my dotfiles repo that I'll upload later.
For me the issue is closed.

**Comment by pter1342** [comment]
@Crisis82 that did the trick, thank you so much it works now
