### ISSUE TITLE
Maximum number of blocks?

### ISSUE THREAD

**Issue by Pyxels** [UtkarshVerma/dwmblocks-async#5]
Is there a maximum number of displayable blocks? 
When I use over 10 blocks, the last ones in the list disappear or visually bug into the middle, but are not clickable.

**Comment by Pyxels** [comment]
Thanks alot
I've been staring at the source code for quite a while now xD
But I don't have enough knowledge about C to understand it fully.

**Comment by UtkarshVerma** [comment]
This bug had me down the rabbit hole for the past day. Apparently, the limitation on the number of blocks was being imposed by signal handlers which are threaded, and therefore simultaneous execution limit is dependent on the CPU (my CPU has 4 cores and 2 threads/core). I had to redo the entire design of the code and got rid of using signals wherever I could.

Now `dwmblocks-async` uses `epoll` so you can go crazy with the number of blocks! I have fixed this through commit #839ccc5. Please test it out and feel free to close the issue if the bug is gone.

You'll have to slightly modify `dwm` source to support the new changes.
https://github.com/UtkarshVerma/dwm/commit/ab805a4429c0aa1ba69520fef7d0fb5bfb8db94f

**Comment by Pyxels** [comment]
Everything works like a charm! Thank you
